sudo: required
language: generic
dist: bionic

env:
  global:
    - ROS_DISTRO=melodic
    - CI_SOURCE_PATH=$(pwd)
    - CI_PARENT_DIR=.travis
  matrix:
    - TEST=build DOCKER_IMAGE=mbf_ci:latest

script:
  - source $CI_PARENT_DIR/$TEST.sh